# Generated by Django 2.2.3 on 2020-07-25 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_txt', models.CharField(max_length=100)),
                ('pub_fecha', models.DateTimeField(verbose_name='Fecha de Publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_txt', models.CharField(max_length=100)),
                ('votos', models.IntegerField(default=0)),
                ('pregunta_txt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Pregunta')),
            ],
        ),
    ]
