# Generated by Django 2.1.5 on 2020-07-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='area',
            field=models.CharField(choices=[('comida', 'Comida'), ('deporte', 'Deporte'), ('salud', 'Salud'), ('farandula', 'Farandula'), ('noticias', 'Noticias'), ('cine', 'Cine'), ('ciencias', 'Ciencias')], default='salud', max_length=2),
        ),
    ]
