# Generated by Django 2.1.5 on 2020-07-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_pregunta_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='area',
            field=models.CharField(choices=[('co', 'Comida'), ('dp', 'Deporte'), ('sa', 'Salud'), ('fa', 'Farandula'), ('no', 'Noticias'), ('cn', 'Cine'), ('ci', 'Ciencias')], default='salud', max_length=2),
        ),
    ]
