# Generated by Django 2.2.3 on 2020-07-28 02:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_auto_20200727_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='pub_fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 2, 9, 26, 938278, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
