# Generated by Django 2.1.5 on 2020-07-27 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_auto_20200727_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='pub_fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 20, 19, 33, 127897, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
