# Generated by Django 2.1.5 on 2020-07-27 23:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0007_auto_20200727_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='pub_fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 23, 11, 58, 55180, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
