# Generated by Django 2.1.5 on 2020-08-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_auto_20200727_2109'),
        ('encuestas', '0008_auto_20200727_2311'),
    ]

    operations = [
    ]
