# Generated by Django 2.1.5 on 2020-08-01 05:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0009_merge_20200801_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='pub_fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 5, 36, 50, 522395, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
