# Generated by Django 2.1.5 on 2020-08-01 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0011_auto_20200801_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='pub_fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 5, 37, 19, 580711, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
