# Generated by Django 2.1.5 on 2020-08-03 02:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0013_auto_20200801_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='area',
            field=models.CharField(choices=[('comida', 'Comida'), ('deporte', 'Deporte'), ('salud', 'Salud'), ('farandula', 'Farandula'), ('noticias', 'Noticias'), ('cine', 'Cine'), ('ciencias', 'Ciencias')], default='salud', max_length=20),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='pub_fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 2, 51, 53, 544636, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
