# Generated by Django 2.1.5 on 2020-08-03 04:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0014_auto_20200802_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='pub_fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 4, 19, 43, 949185, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
